{
 "title": "WebSphere Application Server PMI Metrics Dashboard",
 "description": "Visualize PMI metrics data for your WebSphere Application Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "process_cpu_utilization" } },
   { "name": "cell", "label": "cell", "query": { "query": "process_cpu_utilization" } },
   { "name": "node", "label": "node", "query": { "query": "process_cpu_utilization" } },
   { "name": "server", "label": "server", "query": { "query": "process_cpu_utilization" } },
   { "name": "appname", "label": "appname", "query": { "query": "was_servlet_requests_total" } },
   {
    "name": "jndiname",
    "label": "jndiname",
    "query": {
     "query": "was_connectionpool_free_connections"
    }
   },
   {
    "name": "dur",
    "label": "Duration Range",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   },
   {
    "name": "maxHeapUsageProjection",
    "label": "Max Heap Usage Projection (hours)",
    "query": "1"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "description": "Displays the \"recent CPU usage\" for the Java Virtual Machine processes.",
   "gridPos": { "x": 0, "y": 1, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "process_cpu_utilization{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "description": "The average CPU utilization since the last query. The System CPU load metric value is only available from the nodeagent server from each node.",
   "gridPos": { "x": 12, "y": 1, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "system_cpu_utilization{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\"}",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, node: {{node}}"
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Heap Usage (Percentage)",
   "type": "timeseries",
   "description": "Shows the Heap Usage in graph format.",
   "gridPos": { "x": 0, "y": 11, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"} / jvm_memory_max_bytes{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"} ",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Heap Usage (Percentage)",
   "type": "table",
   "description": "Shows the Heap Usage in graph format in table format.",
   "gridPos": { "x": 12, "y": 11, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"} / jvm_memory_max_bytes{instance=~\"$instance\", node=~\"$node\", server=~\"$server\"} "
    }
   ]
  },
  {
   "title": "Heap Usage (Bytes)",
   "type": "timeseries",
   "description": "The current Heap used by the jvms",
   "gridPos": { "x": 0, "y": 19, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Heap Usage (Bytes)",
   "type": "table",
   "description": "Shows the Heap Usage in table format.",
   "gridPos": { "x": 12, "y": 19, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Increasing Heap Usage Trend Based on Last ${dur}",
   "type": "table",
   "description": "Instances with an increase in heap usage within the last ${dur}.",
   "gridPos": { "x": 0, "y": 27, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "deriv(jvm_memory_used_bytes{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}${dur}) > 0"
    }
   ]
  },
  {
   "title": "Servers That May Reach Max Heap Usage Within [$maxHeapUsageProjection hour(s)] Based on Last $dur",
   "type": "table",
   "description": "Instances projected to reach the max heap size within [$maxHeapUsageProjection hour(s)] based on  data over the last $dur.",
   "gridPos": { "x": 12, "y": 27, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "predict_linear(jvm_memory_used_bytes{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur, $maxHeapUsageProjection * 3600) >  jvm_memory_max_bytes{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Maximum Heap Size",
   "type": "table",
   "description": "An instance's maximum heap size. This value is based on the Xmx value set on admin console for the JVM.",
   "gridPos": { "x": 0, "y": 35, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}"
    }
   ]
  },
  { "title": "Servlets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Slowest Servlets Over Last $dur by Average Response Time",
   "type": "table",
   "description": "The average response time for requests made to a particular servlet based on data over the last $dur.",
   "gridPos": { "x": 0, "y": 44, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "avg(rate(was_servlet_response_time_seconds_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}$dur) / rate(was_servlet_requests_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}$dur)) by (servlet, instance, cell, appname) > 0"
    }
   ]
  },
  {
   "title": "Servlet Request Count Over Last $dur",
   "type": "timeseries",
   "description": "The number of visits made to a servlet instance within the past $dur.",
   "gridPos": { "x": 0, "y": 51, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(was_servlet_requests_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}$dur)) by (servlet, instance, cell, node, server, appname)",
     "legendFormat": "servlet: {{servlet}}, cell: {{cell}}, node: {{node}}, server {{server}}, appname: {{appname}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Average Response Time per Servlet Request Over Last $dur",
   "type": "timeseries",
   "description": "The average response time for a request made to a servlet based on data over the last $dur.",
   "gridPos": { "x": 12, "y": 51, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(was_servlet_response_time_seconds_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}$dur) / rate(was_servlet_requests_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}$dur) ",
     "legendFormat": "servlet: {{servlet}}, cell: {{cell}}, node: {{node}}, server {{server}}, appname: {{appname}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Request Count by Servlet Over Last $dur",
   "type": "timeseries",
   "description": "The sum of visits to a particular servlet over all servers across nodes and instances (i.e. cells) based on data over the last $dur.",
   "gridPos": { "x": 0, "y": 59, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(was_servlet_requests_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}$dur)) by (servlet, appname)",
     "legendFormat": "servlet: {{servlet}}, appname: {{appname}}"
    }
   ]
  },
  {
   "title": "Average Response Time per Request Over Last $dur By Servlet",
   "type": "timeseries",
   "description": "The average response time for requests made to a particular servlet, across all servers nodes and instances (i.e. cells) based on data over the last $dur.",
   "gridPos": { "x": 12, "y": 59, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "avg(rate(was_servlet_response_time_seconds_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}$dur) / rate(was_servlet_requests_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}$dur)) by (servlet, appname)",
     "legendFormat": "servlet: {{servlet}}, appname: {{appname}}"
    }
   ]
  },
  {
   "title": "EJBs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true
  },
  {
   "title": "Average Response Time per EJB Over Last $dur",
   "type": "timeseries",
   "description": "The average response time for an EJB based on data over the last $dur.",
   "gridPos": { "x": 0, "y": 45, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "avg(rate(was_ejb_response_time_seconds_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur) / rate(was_ejb_responses_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)) by (ejb, cell, instance)",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, ejb: {{ejb}}"
    }
   ]
  },
  {
   "title": "Slowest EJBs Over Last $dur by Average Response Time",
   "type": "table",
   "description": "Table that lists the slowest EJBs over the last $dur.",
   "gridPos": { "x": 0, "y": 55, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "avg(rate(was_ejb_response_time_seconds_total{instance=~\"$instance\", \r\ncell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur) / rate(was_ejb_responses_total{instance=~\"$instance\", \r\ncell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)) by (instance, cell, ejb) > 0"
    }
   ]
  },
  {
   "title": "Connection Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true
  },
  {
   "title": "Connections Used Over Last $dur",
   "type": "table",
   "description": "The total number of connection requests that were used over the last $dur. Any connections that are currently in use are not included in this total.",
   "gridPos": { "x": 0, "y": 69, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(was_connectionpool_inUse_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}$dur) > 0"
    }
   ]
  },
  {
   "title": "Connection Requests Queued Over Last $dur",
   "type": "table",
   "description": "The total number of connection requests that waited for a connection because of a full connection pool over the last $dur.",
   "gridPos": { "x": 12, "y": 69, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(was_connectionpool_wait_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}$dur) > 0"
    }
   ]
  },
  {
   "title": "Average Time Usage per Connection",
   "type": "timeseries",
   "description": "The average time any used connection was put in use, based on data over the last ${dur}.",
   "gridPos": { "x": 0, "y": 77, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(was_connectionpool_inUse_time_seconds_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}[$__rate_interval]) / rate(was_connectionpool_inUse_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}[$__rate_interval]) > 0",
     "legendFormat": "{{jndiname}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Average Wait Time per Queued Connection Request",
   "type": "timeseries",
   "description": "The average wait time for any queued connection request, based on data over the last ${dur}.",
   "gridPos": { "x": 12, "y": 77, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(was_connectionpool_wait_time_seconds_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}[$__rate_interval]) / rate(was_connectionpool_wait_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}[$__rate_interval]) > 0",
     "legendFormat": "{{jndiname}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Managed Connections",
   "type": "timeseries",
   "description": "The sum of managed connections in the free, shared, and unshared pools.",
   "gridPos": { "x": 0, "y": 84, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "was_connectionpool_managed_connections{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}",
     "legendFormat": "{{jndiname}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Free & In-Use Connections",
   "type": "timeseries",
   "description": "The number of free connections in the pool.",
   "gridPos": { "x": 0, "y": 92, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "was_connectionpool_free_connections{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}",
     "legendFormat": "free {{jndiname}} @ {{server}}"
    },
    {
     "expr": "was_connectionpool_connectionHandles{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}",
     "legendFormat": "in use {{jndiname}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Connection Create & Close Rate",
   "type": "timeseries",
   "description": "The total number of managed connections created in the past $dur",
   "gridPos": { "x": 0, "y": 100, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(was_connectionpool_create_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}[$__rate_interval])",
     "legendFormat": "create {{jndiname}} @ {{server}}"
    },
    {
     "expr": "rate(was_connectionpool_close_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", jndiname=~\"$jndiname\"}[$__rate_interval])",
     "legendFormat": "close {{jndiname}} @ {{server}}"
    }
   ]
  },
  {
   "title": "SIB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true
  },
  {
   "title": "Message Data (in bytes) Written in the past $dur from the Messaging Engines ",
   "type": "timeseries",
   "description": "The total amount of message data (in bytes) written in the past $dur from the messaging engines.",
   "gridPos": { "x": 0, "y": 86, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(was_sib_communication_me_messageWrite_bytes_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Message Data (in bytes) Read in the past $dur from the Message Engines ",
   "type": "timeseries",
   "description": "The total amount of message data (in bytes) read in the past $dur from the messaging engines.",
   "gridPos": { "x": 12, "y": 86, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(was_sib_communication_me_messageRead_bytes_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Message Data (in bytes) Written in the past $dur from the Clients",
   "type": "timeseries",
   "description": "The total amount of message data (in bytes) written in the past $dur from the Clients",
   "gridPos": { "x": 0, "y": 94, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(was_sib_communication_client_messageWrite_bytes_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Message Data (in bytes) Read in the past $dur from the Clients",
   "type": "timeseries",
   "description": "The total amount of message data (in bytes) read in the past $dur from the Clients",
   "gridPos": { "x": 12, "y": 94, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(was_sib_communication_client_messageRead_bytes_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Messages Produced by Queue in the last $dur",
   "type": "timeseries",
   "description": "Messages Produced by Queue in the last $dur",
   "gridPos": { "x": 0, "y": 102, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(was_sib_queue_messageProduced_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)) by (instance, cell, queue)",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, queue: {{queue}}"
    }
   ]
  },
  {
   "title": "Messages Consumed by Queue in the last $dur",
   "type": "timeseries",
   "description": "Messages Consumed by Queue in the last $dur",
   "gridPos": { "x": 12, "y": 102, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(was_sib_queue_messageConsumed_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)) by (instance, cell, queue)",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, queue: {{queue}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true
  },
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "description": "A session is considered active if the application server is processing a request that uses that user session.",
   "gridPos": { "x": 0, "y": 88, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "was_session_active_sessions{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}",
     "legendFormat": "instance: {{instance}}, appname: {{appname}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Live  Sessions",
   "type": "timeseries",
   "description": "A session is considered live if the session is loaded into memory by the application server.",
   "gridPos": { "x": 0, "y": 98, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "was_session_live_sessions{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}",
     "legendFormat": "instance: {{instance}}, appname: {{appname}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Invalidated Sessions in the past $dur",
   "type": "timeseries",
   "description": "The number of sessions that were invalidated.",
   "gridPos": { "x": 0, "y": 108, "w": 12, "h": 12 },
   "targets": [
    {
     "expr": "increase(was_session_invalidated_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}$dur)",
     "legendFormat": "instance: {{instance}}, appname: {{appname}},  cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Created Sessions in the past $dur",
   "type": "timeseries",
   "description": "Created sessions in the last $dur",
   "gridPos": { "x": 12, "y": 108, "w": 12, "h": 12 },
   "targets": [
    {
     "expr": "increase(was_session_create_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\", appname=~\"$appname\"}$dur)",
     "legendFormat": "instance: {{instance}}, appname: {{appname}},  cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true
  },
  {
   "title": "Largest Thread Pool Sizes Over Last $dur",
   "type": "table",
   "description": "The size of the thread pools in each server, based on data over the last $dur.",
   "gridPos": { "x": 0, "y": 98, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "max_over_time(was_threadpool_size{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "description": "The number of threads that are actively running tasks.",
   "gridPos": { "x": 0, "y": 106, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "was_threadpool_active_threads{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}",
     "legendFormat": "instance: {{instance}}, pool: {{pool}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Thread Pool Size",
   "type": "timeseries",
   "description": "The size of the thread pool in each server.",
   "gridPos": { "x": 0, "y": 113, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "was_threadpool_size{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}",
     "legendFormat": "instance: {{instance}}, pool: {{pool}},cell: {{cell}},  node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Declared Hung Threads in the past $dur",
   "type": "timeseries",
   "description": "The number of threads declared hung in the last $dur",
   "gridPos": { "x": 0, "y": 120, "w": 12, "h": 11 },
   "targets": [
    {
     "expr": "increase(was_threadpool_declaredThreadHungs_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)",
     "legendFormat": "instance: {{instance}}, pool: {{pool}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Concurrent Hung Threads",
   "type": "timeseries",
   "description": "The number of concurrent hung threads",
   "gridPos": { "x": 12, "y": 120, "w": 12, "h": 11 },
   "targets": [
    {
     "expr": "was_threadpool_concurrentHung_threads{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}",
     "legendFormat": "instance: {{instance}}, pool: {{pool}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "collapsed": true
  },
  {
   "title": "Time Spent Garbage Collecting During Last $dur",
   "type": "table",
   "description": "A table reporting the portion of time a specific server has spent Garbage Collecting in the last $dur.",
   "gridPos": { "x": 0, "y": 109, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "rate(jvm_gc_duration_seconds_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)"
    }
   ]
  },
  {
   "title": "Time per Garbage Collection Cycle $dur moving average",
   "type": "timeseries",
   "description": "The average time a server took on garbage collection, based on data over the last $dur.",
   "gridPos": { "x": 0, "y": 117, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "rate(jvm_gc_duration_seconds_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur) / rate(jvm_gc_total{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}$dur)",
     "legendFormat": "instance: {{instance}}, cell: {{cell}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Other JVM Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "collapsed": true
  },
  {
   "title": "JVM Uptime",
   "type": "table",
   "description": "The time elapsed since the start of the JVM.",
   "gridPos": { "x": 0, "y": 110, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=~\"$instance\", cell=~\"$cell\", node=~\"$node\", server=~\"$server\"}"
    }
   ]
  }
 ]
}